name: moneyapp3
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  easy_localization: ^3.0.7
  uuid: ^3.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  decimal: ^2.2.0
  http: ^1.2.2
  go_router: ^14.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_crashlytics: ^4.1.3
  cloud_functions: ^5.1.3
  injectable: ^2.5.0
  get_it: ^8.0.1
  injectable_generator: ^2.6.2
  dart_mappable: ^4.3.0
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
  flutter_flavor: ^3.1.3
  stacked_shared: ^1.4.2
  share_plus: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  intl_utils: ^2.5.0
  flutter_gen: ^5.8.0
  intl_translation: ^0.20.0
  flutter_hooks: ^0.18.0
  flutter_lints: ^2.0.0
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/

flutter_intl:
  enabled: true
  flutter_lints: ^4.0.0
